version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: prompt-manager:${TAG:-latest}
    restart: unless-stopped
    ports:
      - "${PORT:-3001}:3001"
    volumes:
      - prompt_data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DB_PATH=/app/data
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3001/api/prompts"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  prompt_data:
    name: prompt-manager-prod-data
