version: '3.8'

services:
  app:
    build: 
      context: .
      target: builder
    ports:
      - "5173:5173"  # Vite dev server
      - "3001:3001"  # Express backend
    volumes:
      - .:/app
      - /app/node_modules
      - sqlite_data:/app/data
    environment:
      - NODE_ENV=development
      - VITE_DEV_SERVER_HOST=0.0.0.0
      - VITE_DEV_SERVER_PORT=5173
      - DB_PATH=/app/data
      - PORT=3001
    command: npm start
    # Add healthcheck to ensure service is running properly
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:5173"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  sqlite_data:
    name: prompt-manager-sqlite-data
